[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true

[dependencies]
forge-std = "forge-std/1.9.3"
openzeppelin-contracts = "openzeppelin/openzeppelin-contracts@v5.0.2"
zk-email-contracts = "zkemail/zk-email-verify@v6.4.2"

[profile.remappings]
"@std/" = "lib/forge-std/src/"
"@openzeppelin/" = "lib/openzeppelin-contracts/"
"@zk-email/" = "lib/zk-email-verify/"

[fuzz]
runs = 256

[invariant]
runs = 256 
